# Generated by Django 4.2 on 2023-04-26 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('langueage', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='photos/%y/%m')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api_Immfly.channel')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField(default=0)),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_Immfly.channel')),
            ],
        ),
        migrations.CreateModel(
            name='Metadatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_Immfly.content')),
            ],
        ),
    ]
