# Generated by Django 4.2 on 2023-04-26 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_Immfly', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='channel_id',
            new_name='channel',
        ),
        migrations.RenameField(
            model_name='metadatos',
            old_name='content_id',
            new_name='content',
        ),
    ]
