# Generated by Django 4.2 on 2023-04-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_Immfly', '0002_rename_channel_id_content_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='langueage',
            field=models.CharField(max_length=255),
        ),
    ]
